project_prueba/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tareas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'
    )),
]

tareas/urls.py
from django.urls import path, include
from tareas import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_tarea/', views.create_tarea, name='crear-tarea'),
    path('list_tareas/', views.list_tareas, name='list-tareas'),
    path('check_tarea/<int:id_tarea>/', views.check_tarea, name='check-tarea'),
]

tareas/models.py
from django.db import models

# Create your models here.
class tarea(models.Model):
	nombre = models.CharField(max_length=100)
	fecha_creado = models.DateField()
	fecha_venc = models.DateField()
	coment = models.CharField(max_length=300)
	priori = models.CharField(max_length=20)
	resuelta = models.BooleanField(default=False)

tareas/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import tarea
import datetime
import json
from django.http import HttpResponse, JsonResponse
from django.core import serializers

# Create your views here.
@login_required(login_url='accounts/login')
def index(request):
	return render(request, 'tareas/index.html', status=200)

def create_tarea(request):
	now = datetime.datetime.now()

	if request.method == 'POST':
		nom_tarea = request.POST['tarea']
		print(request.POST['tarea'])
		response_data = {}
		tarea_obj = tarea(nombre=nom_tarea, fecha_creado=now, fecha_venc=request.POST['fecha_venc'], coment='comment',priori=request.POST['priori'])
		tarea_obj.save()
		response_data['result'] = 'Create post successful!'
		response_data['tareapk'] = tarea_obj.pk
		response_data['tarea'] = tarea_obj.nombre
		#response_data['creado'] = tarea_obj.created.strftime('%B %d, %Y %I:%M %p')
		return HttpResponse(json.dumps(response_data),content_type="application/json")
	else:
		return HttpResponse(json.dumps({"nothing to see": "this isn't happening"}),content_type="application/json")

def list_tareas(request):
	data = serializers.serialize("json", list(tarea.objects.filter(resuelta=False)))
	return HttpResponse(data,content_type="application/json")

def check_tarea(request, id_tarea):
	t = tarea.objects.get(id=id_tarea)
	t.resuelta = True  # change field
	t.save() # this will update only
	print(t)
	data = serializers.serialize("json", tarea.objects.filter(id=id_tarea))
	return HttpResponse(data,content_type="application/json")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.2.1/css/bootstrap.min.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome/5.6.3/css/all.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">

	<script type="text/javascript" src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap-4.2.1/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'moment.js/2.24.0/moment.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'moment.js/2.24.0/moment-with-locales.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
    <div class="container">
  <a class="navbar-brand" href="#">TodoList</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
    {% if user.is_authenticated %}
    <a class="nav-link" href="#">{{ user.username }} <i class="fas fa-user"></i></a>
    {% endif %}
    </ul>
      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">Salir <i class="fas fa-sign-out-alt"></i></a>
      {% endif %}
  </div>
  </div>
</nav>
<div class="container mt-5">
	<div class="row">
		{% block content %}
    	{% endblock %}
	</div>
</div>
  </body>
</html>

templates/tareas/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} tareas {% endblock %}

{% block content %}
<div class="col-md-3">
	<div><span class="h5">TodoList Demo</span></div>
	Todas<br>
	Completadas<br>
	Pendientes<br>
</div>
<div class="col-md-9">
	<div class="list-tareas"></div>
	<button class="btn btn-primary add_tarea mt-3"><i class="fas fa-plus"></i> Agregar Tarea</button>
	<div class="tarea mt-3">
		<form method="post" action="" id="form-save-tarea">
			{% csrf_token %}
			Nombre: <input class='form-control mb-2' type='text' name="tarea" id="id_tarea" />
			Programar: <input class='form-control mb-2' type='datetime' name="fecha_venc" id="id_fecha_venc" />
			Prioridad: <select class="form-control mb-2" name="priori" id="id_priori">
				<option value="Prioridad 1">Prioridad 1</option>
				<option value="Prioridad 2">Prioridad 2</option>
				<option value="Prioridad 3">Prioridad 3</option>
			</select>
			<input type='submit' class='btn btn-success' value='Guardar'/>
			<a class='cancelar'>Cancelar</a>
		</form>
		<div id="results"></div>
	</div>
</div>
<input type="hidden" name="" value="{{ csrf_token }}" id="token">
<input type="hidden" name="" id="now" value="{% now 'c' %}">
<script type="text/javascript" src="{% static 'assets/js/tareas/crear_tarea.js' %}"></script>
{% endblock %}